name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image_uri: ${{ steps.set-image-uri.outputs.image_uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set IMAGE_URI
        id: set-image-uri
        run: |
          # Hardcode your ECR registry if login-ecr output is empty
          IMAGE_URI="977098999802.dkr.ecr.us-east-1.amazonaws.com/portfolio"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "IMAGE_URI is set to $IMAGE_URI"

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_URI }}:${{ github.run_number }} .

      - name: Scan local image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_URI }}:${{ github.run_number }}
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ env.IMAGE_URI }}:${{ github.run_number }}
          docker tag ${{ env.IMAGE_URI }}:${{ github.run_number }} ${{ env.IMAGE_URI }}:latest
          docker push ${{ env.IMAGE_URI }}:latest

  deploy:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export IMAGE_URI="${{ needs.build-and-scan.outputs.image_uri }}"
            export IMAGE_TAG="${{ github.run_number }}"
            export AWS_REGION="${{ vars.AWS_REGION }}"

            echo "Using image: $IMAGE_URI:$IMAGE_TAG"

            # Login to ECR on remote host (host already has AWS credentials)
            aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$(echo $IMAGE_URI | cut -d'/' -f1)"

            # Pull the Docker image
            docker pull "$IMAGE_URI:$IMAGE_TAG"

            # Stop/remove old container if exists
            docker rm -f resume || true

            # Run the new container
            docker run -d --name resume -p 8080:5001 "$IMAGE_URI:$IMAGE_TAG"
